CREATE DATABASE FINAL
CREATE TABLE EMPLOYEE
(
ENAME VARCHAR(30) NOT NULL PRIMARY KEY,
CNAME VARCHAR(30) NOT NULL,
STREET VARCHAR (50),
HOMETOWN VARCHAR(30),
SALARY decimal (18,2) null
)

INSERT INTO EMPLOYEE(ENAME, CNAME, STREET, HOMETOWN, SALARY)
VALUES ('MURAD', 'BRACK BANK', '0/2 MONIPURIPARA', 'BOGRA', 30000),
('HABIB', 'BANGLADESH BANK', '0/5 MALIBAG', 'KURIGRAM', 40000),
('BITHI', 'RUPALI BANK', '0/2 AMIN BAZAR', 'BOGRA', 35000),
('RAKHI', 'SONALI BANK', '5/2 MIRPUR', 'RAJSHAHI', 18000),
('ROWSHAN', 'BRACK BANK', '3/2 MONIPURIPARA', 'BOGRA', 25000)
INSERT INTO EMPLOYEE(ENAME, CNAME, STREET, HOMETOWN, SALARY)
VALUES ('Siam', 'BRACK BANK', '53/2 shukrabad', 'DHAKA', 45000)

CREATE TABLE COMPANY
(
CNAME VARCHAR(50) NOT NULL PRIMARY KEY,
CITY VARCHAR (30),
ADDRESS VARCHAR (20),
EMP_COUNT INT

)

INSERT INTO COMPANY (CNAME, CITY, ADDRESS, EMP_COUNT)
VALUES ('BANGLADESH BANK', 'DHAKA', 'BANGLA MOTOR', 30),
('BRACK BANK', 'DHAKA', 'NILKHET', 30),
('RUPALI BANK', 'DHAKA', 'GULSHAN', 30),
('SONALI BANK', 'DHAKA', 'POLTON', 30),
('DBL BANK', 'DHAKA', 'DHANMONDI', 30)

SELECT *FROM EMPLOYEE
SELECT *FROM COMPANY


UPDATE EMPLOYEE SET SALARY=60000 WHERE ENAME='MURAD'


---A
SELECT ENAME,STREET, HOMETOWN FROM EMPLOYEE WHERE CNAME='BRACK BANK' AND SALARY>50000

--B
SELECT CNAME FROM EMPLOYEE WHERE SALARY > all (SELECT AVG(SALARY) FROM EMPLOYEE GROUP BY CNAME)

SELECT CNAME  FROM EMPLOYEE where  AVG(SALARY) > 20000   GROUP BY CNAME

SELECT CNAME FROM EMPLOYEE GROUP BY  (SELECT AVG(SALARY) FROM EMPLOYEE GROUP BY CNAME)
SELECT CNAME,SALARY FROM EMPLOYEE WHERE SALARY > ((SELECT AVG(SALARY) FROM EMPLOYEE))


--C
SELECT ENAME FROM EMPLOYEE WHERE HOMETOWN = ALL( SELECT HOMETOWN FROM EMPLOYEE WHERE CNAME='BRACK BANK')

--ALTER SlN 1
SELECT EMPLOYEE.ENAME FROM EMPLOYEE,COMPANY WHERE EMPLOYEE.HOMETOWN = COMPANY.CITY AND EMPLOYEE.CNAME=COMPANY.CNAME


---D
SELECT ENAME FROM EMPLOYEE WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE)

--Alter SLN 1
SELECT * FROM EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE) order by SALARY desc

--E
SELECT COUNT(ENAME) FROM EMPLOYEE WHERE CNAME LIKE '%BANK'